# Generated by Django 3.2 on 2026-03-02 00:00
from django.db import migrations
from django.utils.text import slugify


def fill_slugs(apps, schema_editor):
    Subject = apps.get_model('courses', 'Subject')
    for subj in Subject.objects.filter(slug__in=['', None]):
        subj.slug = slugify(subj.title) or f"subject-{subj.pk}"
        subj.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_content_options_alter_module_options_and_more'),
    ]

    operations = [
        migrations.RunPython(fill_slugs, migrations.RunPython.noop),
    ]
