# Generated by Django 6.0.2 on 2026-03-02 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_course_students"),
        ("courses", "0004_fill_empty_subject_slugs"),
    ]

    operations = []
